import { PRODUCT } from '../../types/products'

export const PRODUCTS: PRODUCT[] = [{
  id: '1',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active',
},
{
  id: '2',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'paused'
},
{
  id: '3',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'vacation'
},
{
  id: '4',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
},
{
  id: '5',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'paused'
},
{
  id: '6',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
},
{
  id: '7',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
},
{
  id: '8',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'paused',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '9',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '10',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'vacation'
}, {
  id: '11',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '12',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '13',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '14',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '15',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}, {
  id: '16',
  type: 'remera',
  name: 'camiseta nike GOD',
  price: { USD: 10, ARS: 10000 },
  files: ['/img/camiseta.jpg'],
  size: 'M',
  color: 'rojo',
  description: 'camiseta nike GOD',
  gender: 'hombre',
  stock: 10,
  inSale: false,
  status:'active'
}]